development:
  adapter: postgresql
  encoding: unicode
  database: item_reviewer_development
  pool: 5
  username: item_reviewer
  password: item_reviewer_password

test:
  adapter: postgresql
  encoding: unicode
  database: item_reviewer_test
  pool: 5
  username: item_reviewer
  password: item_reviewer_password
